### ISSUE TITLE
[Request] Launch flashcard with TWL clock speed and TWLoader boot screen customization.

### ISSUE THREAD

**Issue by Daeymon** [Robz8/DSiMenuPlusPlus-Launcher#12]
I know NTR Launcher can launch with the higher speeds, but TWLoader had some nice options with boot screen customization while enhancing clock speeds. Would like to see this to come to the launcher.

**Comment by Robz8** [comment]
You can change clock speed in DSiMenu++ settings.

**Comment by Daeymon** [comment]
Unless I'm doing it wrong, DSiMenu++ has no clock speed settings when being used on a flashcart.

**Comment by Robz8** [comment]
That's normal. You can only set the clock speed on the SD card, but, you can launch your flashcard with TWL clock speed, if set in the settings.

**Comment by Daeymon** [comment]
I just gave this a go. And I apologise if I've misunderstood and am really doing this wrong. The SD Card version of DSiMenu++ can only launch the flashcart itself, not the games on it.

So I use the launcher, which then launches DSiMenu++ on the SD Card, which has the TWL clock speed enabled, which then in turn launches the flashcart, which then loads the local version of DSiMenu++ on the flashcart :S The version of DSiMenu++ on the SD Card just seems like an unnecessary go between to achieve TWL clock speeds on the flashcart version of DSiMenu.
