### ISSUE TITLE
Streamline Launch of DSiMenuPlusPlus

### ISSUE THREAD

**Issue by MarioKartFan** [Robz8/DSiMenuPlusPlus-Launcher#7]
Hello Robz8, is there anyway to streamline the launching of DSiMenuPlusPlus?  Right now, the launcher flashes the Homebrew Channel image, then pops up the 1.1 menu (the settings in which I have never touched after the initial launch).  It would be great if there was a way to boot directly into your incredible DSiMenuPlusPlus.  Thanks for all you do.

**Comment by RonnChyran** [comment]
+1, autobooting DSiMenu++ would make things a lot more seamless. Perhaps you could hold `SELECT` on starting the app to access settings like Luma3DS?

**Comment by MarioKartFan** [comment]
Features added in 2.0 address this concern.  Would still be nice to not have the Homebrew logo splash, but otherwise, this has been addressed.
