### ISSUE TITLE
Touchscreen support for the Launcher

### ISSUE THREAD

**Issue by Andrefpvs** [Robz8/DSiMenuPlusPlus-Launcher#9]
Hi Robz8, thank you for your work!

I was wondering if it is possible to add touchscreen support to the launcher, so for example one could tap "Start last-ran ROM" instead of having to press Right+A.

Thank you

**Comment by Robz8** [comment]
Implemented in v2.0.0.

**Comment by Andrefpvs** [comment]
Top work. Thank you!
